# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - josh-flask

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: josh-flask # set this to your application's name
  WORKING_DIRECTORY: '.'         # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: '3.7' 
  STARTUP_COMMAND: 'application.py'           # set this to the startup command required to start the gunicorn server. default it is empty
  
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'josh-flask'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a461401bce234ccfa6e691530ddd498c }}
